### ISSUE TITLE
 Invalid numeric literal

### ISSUE THREAD

**Issue by jose123455587** [Sanix-Darker/AntiDDOS-system#5]
Invalid numeric literal in C:\xampp\htdocs\test\anti_ddos\files\check.txt on line 1
How i can fix it ?

**Comment by Sanix-Darker** [comment]
Hi @jose123455587 first, it's look like you are using xamp, am not sure about it, but i think, this issue is cause by a version of your PHP or your Apache server, on my side am using (WampServer 3.1 with PHP 5.6.3 ).
Please can you try with theese parameters or give us your server config, so that we can check were is the problem please?

**Comment by jose123455587** [comment]
I'm using php 7.2.9 and Apache 2 and yes I'm using xampp

**Comment by Sanix-Darker** [comment]
Hi @jose123455587 , did you finally found a fix for your xampp?

**Comment by Sanix-Darker** [comment]
Closing this issue due to any updates yet in the Error!
